# These are supported funding model platforms

github: [kinglove58]
patreon: [kinglove58]
open_collective: [kinglove58]
ko_fi: [kinglove58]
tidelift: [kinglove58]
community_bridge: [kinglove58]
liberapay: [kinglove58]
issuehunt: [kinglove58]
lfx_crowdfunding: [kinglove58]
polar: [kinglove58]
buy_me_a_coffee: [kinglove58]
thanks_dev: [kinglove58]
custom: [https://kinglove58.gumroad.com/coffee]
